### PR TITLE
CLI interface polish

### PR DESCRIPTION
**Pull request by alloy**
The last commit is a suggestion, do you think it’s too much? (Note that I also haven’t actually tested that this works yet, so please do check if you spot any errors.)

### CODE REVIEW

**Comment by alloy** [comment]
@kastermester ^

**Comment by kastermester** [comment]
Seems good! :)

**Comment by kastermester** [comment]
Have you had anyone from the Relay team look at your branch yet, or are you still wanting to polish it off some more?

I'm thinking it might be so far ahead that it can be sent as a PR on the official repo, just marked as a WIP, just so we can get some more feedback. Then, once we have everything running as it should with the typescript language plugin we can mark it ready for merging (assuming the relay team is happy with it).

What do you think?

**Comment by alloy** [comment]
I decided to revert the babelrc thing for now, it was just a bit too much and I don’t want the PR to Relay would be held up by side stuff like this.

**Comment by kastermester** [comment]
Makes sense :)

**Comment by alloy** [comment]
Yep, I think that with the addition of `artifactDirectory` in we an make that upstream PR. I’ll first want to make sure everything works in the example as expected, though.

**Comment by kastermester** [comment]
> Yep, I think that with the addition of artifactDirectory in we an make that upstream PR. I’ll first want to make sure everything works in the example as expected, though.

That was my initial thoughts as well, but perhaps getting a feel for whether or not they like the general idea of what we're doing would be good? That's why I figured we could make an upstream PR marked as a WIP, or perhaps tag some of the relay people in the other PR?

**Comment by alloy** [comment]
Yeah I’m not going to finish all of the plugin interface docs nor rebase yet, but I do wanna have it be in a testable state, for if they so wish to do.

**Pull request merged**
